## Python Programming Basic A8
### 1.	Write a Python Program to Add Two Matrices?
#### Answer : 

In [6]:
import numpy as np

M1 = np.array([[1,2,3],
        [4,6,8],
        [4,8,1]])
M2 = np.array([[3,5,7],
        [2,3,7],
        [4,7,1]])

M3 = np.add(M1,M2)
print("The Sum of two Matrices \n\n{}  and \n\n{}  is \n\n{} ".format(M1,M2,M3))

The Sum of two Matrices 

[[1 2 3]
 [4 6 8]
 [4 8 1]]  and 

[[3 5 7]
 [2 3 7]
 [4 7 1]]  is 

[[ 4  7 10]
 [ 6  9 15]
 [ 8 15  2]] 


### 2.	Write a Python Program to Multiply Two Matrices?
#### Answer :

In [7]:
import numpy as np

M1 = np.array([[1,2,3],
        [4,6,8],
        [4,8,1]])
M2 = np.array([[3,5,7],
        [2,3,7],
        [4,7,1]])

M3 = np.dot(M1,M2)
print("The Sum of two Matrices \n\n{}  and \n\n{}  is \n\n{} ".format(M1,M2,M3))

The Sum of two Matrices 

[[1 2 3]
 [4 6 8]
 [4 8 1]]  and 

[[3 5 7]
 [2 3 7]
 [4 7 1]]  is 

[[19 32 24]
 [56 94 78]
 [32 51 85]] 


### 3.	Write a Python Program to Transpose a Matrix?
#### Answer :

In [9]:
M = [[12, 1, 5],
    [4 , 5, 6],
    [3 , 7, 3]]

transpose = [[M[i][j] for i in range(len(M))] for j in range(len(M[0]))]

for T in transpose:
   print(T)

[12, 4, 3]
[1, 5, 7]
[5, 6, 3]


### 4.	Write a Python Program to Sort Words in Alphabetic Order?
#### Answer :

In [13]:
string = input("Enter a string: ")

a = string.split()
a.sort()
for i in a:
    print(i)

Enter a string: I AM VINAY
AM
I
VINAY


### 5.	Write a Python Program to Remove Punctuation From a String?
#### Answer :

In [14]:
def removep():
    punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
    string = input('Enter a String: ')
    final = ''
    for i in string:
        if i not in punctuations:
            final += i
    print(final)
    
removep()

Enter a String: "I"- "AM" - "VINAY!"
I AM  VINAY
